{% set name = "ldcpy" %}
{% set version = "0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2edbcd72081cd00fbb4d138980779a09f045cc4609774b48d4accd8ca5ccc60
  
build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - cmocean
    - cython
    - dask
    - jupyterlab
    - matplotlib-base
    - netcdf4
    - numpy
    - opencv
    - pip
    - python
    - scikit-image
    - scipy
    - xarray
    - xrft
    - cartopy
    - nc-time-axis

test:
  imports:
    - ldcpy

about:
  home: https://github.com/NCAR/ldcpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A utility for gathering and plotting metrics from NetCDF files using the Pangeo stack.

  description: |
    A utility for gathering and plotting metrics from NetCDF files using the Pangeo stack.
  doc_url: https://ldcpy.readthedocs.io/
  dev_url: https://github.com/NCAR/ldcpy

extra:
  recipe-maintainers:
    - pinarda
